version: '3.8'

services:
  zk-1:
    image: bitnami/zookeeper:3.4.10
    container_name: zk-1
    restart: unless-stopped
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOO_SERVER_ID: 1
      ZOO_SERVERS: server.1=zk-1:2888:3888
    ports:
      - "2181:2181" # Client Port 2181 clients used to communicate with the server.
    networks:
      - flink-network

  kafka1:
    image: wurstmeister/kafka:latest
    restart: "on-failure"
    container_name: broker-1
    depends_on:
      - zk-1
    ports:
      - "9092:9092"
      - "7071:7071"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_HOST_NAME: kafka1
      KAFKA_ZOOKEEPER_CONNECT: "zk-1:2181"
      KAFKA_BROKER_RACK: "r1"
      KAFKA_LISTENERS: INTERNAL://:29092,EXTERNAL://:9092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka1:29092,EXTERNAL://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,DOCKER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_ZOOKEEPER_SESSION_TIMEOUT: "6000"
      KAFKA_RESTART_ATTEMPTS: "10"
      KAFKA_LOG_RETENTION_HOURS: 3
      KAFKA_LOG_ROLL_HOURS: 1
      KAFKA_NUM_PARTITIONS: 20
    networks:
      flink-network:

  jobmanager:
    image: flink:latest
    container_name: flink-jobmanager
    hostname: jobmanager
    ports:
      - "8081:8081" # Flink's Web UI
    environment:
      - FLINK_PROPERTIES=
      - jobmanager.rpc.address=jobmanager
    command: jobmanager
    networks:
      - flink-network

  taskmanager:
    image: flink:latest
    container_name: flink-taskmanager
    hostname: taskmanager
    environment:
      - FLINK_PROPERTIES=
      - jobmanager.rpc.address=jobmanager
      - taskmanager.numberOfTaskSlots=1
    command: taskmanager
    depends_on:
      - jobmanager
    networks:
      - flink-network


networks:
  flink-network:
    driver: bridge



